# Generated by Django 5.1 on 2025-11-01 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_fundraiser_owner_pledge_supporter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='anonymous',
            new_name='anonomous',
        ),
    ]
